name: Build MDriven Server Variants

on:
  push:
    branches:
      - "main"
    paths:
      - "**.Dockerfile"

env:
  IMAGE_NAME: ${{vars.DOCKERHUB_USERNAME}}/mdriven-server

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Linux AMD64
        uses: docker/build-push-action@v6
        with:
          context: ./docker/builds
          file: ./docker/builds/mdriven-server/linux/Amd64.Dockerfile
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: ${{env.IMAGE_NAME}}:linux-amd64

  build-linux-arm64:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Linux ARM64
        uses: docker/build-push-action@v6
        with:
          context: ./docker/builds
          file: ./docker/builds/mdriven-server/linux/Arm64.Dockerfile
          platforms: linux/arm64
          no-cache: true
          push: true
          tags: ${{env.IMAGE_NAME}}:linux-arm64
            
  build-linux-musl:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Linux MUSL
        uses: docker/build-push-action@v6
        with:
          context: ./docker/builds
          file: ./docker/builds/mdriven-server/linux/Musl.Dockerfile
          no-cache: true
          push: true
          tags: ${{env.IMAGE_NAME}}:musl
      
            
  create-manifest:
    needs: [build-linux-amd64, build-linux-arm64]
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Create and Push Manifest
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:linux-amd64 \
            ${{ env.IMAGE_NAME }}:linux-arm64 
      


